services:
  app:
    build:
      context: .
      dockerfile: dockerfile.app
    develop:
      watch:
        - action: rebuild
          path: ./package.json
        - action: rebuild
          path: ./src/adapter/postgres/migration
        - action: rebuild
          path: ./src/adapter/postgres/drizzle
    volumes:
      - ./src:/app/src
      - /etc/letsencrypt:/etc/letsencrypt:ro
    ports:
      - ${APP_PORT}:${APP_PORT}
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:5432
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 3s
      timeout: 3s
      retries: 3
      start_period: 15s
      start_interval: 3s

volumes:
  postgres_data:
