import * as schema from '../drizzle/schema'
import { InferInsertModel } from 'drizzle-orm'
import { Currency, Region } from 'src/shared/enum/enum'

export const marketTrendSeeds: InferInsertModel<typeof schema.marketTrends>[] =
  [
    // 헬스케어 - 국내 시장 트렌드
    {
      id: 1,
      marketStatsId: 1,
      region: Region.DOMESTIC,
      year: 2021,
      volume: 25000000000,
      currency: Currency.KRW,
      growthRate: 22,
      source: 'https://example.com/korean-digital-health-2021',
    },
    {
      id: 2,
      marketStatsId: 1,
      region: Region.DOMESTIC,
      year: 2022,
      volume: 30000000000,
      currency: Currency.KRW,
      growthRate: 20,
      source: 'https://example.com/korean-digital-health-2022',
    },
    {
      id: 3,
      marketStatsId: 1,
      region: Region.DOMESTIC,
      year: 2023,
      volume: 36000000000,
      currency: Currency.KRW,
      growthRate: 28,
      source: 'https://example.com/korean-digital-health-2023',
    },
    {
      id: 4,
      marketStatsId: 1,
      region: Region.DOMESTIC,
      year: 2024,
      volume: 45000000000,
      currency: Currency.KRW,
      growthRate: 25,
      source: 'https://example.com/korean-digital-health-2024',
    },
    {
      id: 5,
      marketStatsId: 1,
      region: Region.DOMESTIC,
      year: 2025,
      volume: 56000000000,
      currency: Currency.KRW,
      growthRate: 24,
      source: 'https://example.com/korean-digital-health-forecast',
    },
    // 헬스케어 - 글로벌 시장 트렌드
    {
      id: 6,
      marketStatsId: 1,
      region: Region.GLOBAL,
      year: 2021,
      volume: 140000000000,
      currency: Currency.USD,
      growthRate: 18,
      source: 'https://example.com/global-digital-health-2021',
    },
    {
      id: 7,
      marketStatsId: 1,
      region: Region.GLOBAL,
      year: 2022,
      volume: 170000000000,
      currency: Currency.USD,
      growthRate: 21,
      source: 'https://example.com/global-digital-health-2022',
    },
    {
      id: 8,
      marketStatsId: 1,
      region: Region.GLOBAL,
      year: 2023,
      volume: 210000000000,
      currency: Currency.USD,
      growthRate: 25,
      source: 'https://example.com/global-digital-health-2023',
    },
    {
      id: 9,
      marketStatsId: 1,
      region: Region.GLOBAL,
      year: 2024,
      volume: 260000000000,
      currency: Currency.USD,
      growthRate: 24,
      source: 'https://example.com/global-digital-health-2024',
    },
    {
      id: 10,
      marketStatsId: 1,
      region: Region.GLOBAL,
      year: 2025,
      volume: 320000000000,
      currency: Currency.USD,
      growthRate: 23,
      source: 'https://example.com/global-digital-health-forecast',
    },
    // 환경 모니터링 - 국내 시장 트렌드
    {
      id: 11,
      marketStatsId: 2,
      region: Region.DOMESTIC,
      year: 2021,
      volume: 15000000000,
      currency: Currency.KRW,
      growthRate: 15,
      source: 'https://example.com/korean-env-monitoring-2021',
    },
    {
      id: 12,
      marketStatsId: 2,
      region: Region.DOMESTIC,
      year: 2022,
      volume: 18000000000,
      currency: Currency.KRW,
      growthRate: 20,
      source: 'https://example.com/korean-env-monitoring-2022',
    },
    {
      id: 13,
      marketStatsId: 2,
      region: Region.DOMESTIC,
      year: 2023,
      volume: 22000000000,
      currency: Currency.KRW,
      growthRate: 22,
      source: 'https://example.com/korean-env-monitoring-2023',
    },
    {
      id: 14,
      marketStatsId: 2,
      region: Region.DOMESTIC,
      year: 2024,
      volume: 27000000000,
      currency: Currency.KRW,
      growthRate: 23,
      source: 'https://example.com/korean-env-monitoring-2024',
    },
    {
      id: 15,
      marketStatsId: 2,
      region: Region.DOMESTIC,
      year: 2025,
      volume: 33000000000,
      currency: Currency.KRW,
      growthRate: 22,
      source: 'https://example.com/korean-env-monitoring-forecast',
    },
    // 환경 모니터링 - 글로벌 시장 트렌드
    {
      id: 16,
      marketStatsId: 2,
      region: Region.GLOBAL,
      year: 2021,
      volume: 80000000000,
      currency: Currency.USD,
      growthRate: 14,
      source: 'https://example.com/global-env-monitoring-2021',
    },
    {
      id: 17,
      marketStatsId: 2,
      region: Region.GLOBAL,
      year: 2022,
      volume: 95000000000,
      currency: Currency.USD,
      growthRate: 19,
      source: 'https://example.com/global-env-monitoring-2022',
    },
    {
      id: 18,
      marketStatsId: 2,
      region: Region.GLOBAL,
      year: 2023,
      volume: 115000000000,
      currency: Currency.USD,
      growthRate: 21,
      source: 'https://example.com/global-env-monitoring-2023',
    },
    {
      id: 19,
      marketStatsId: 2,
      region: Region.GLOBAL,
      year: 2024,
      volume: 135000000000,
      currency: Currency.USD,
      growthRate: 17,
      source: 'https://example.com/global-env-monitoring-2024',
    },
    {
      id: 20,
      marketStatsId: 2,
      region: Region.GLOBAL,
      year: 2025,
      volume: 165000000000,
      currency: Currency.USD,
      growthRate: 22,
      source: 'https://example.com/global-env-monitoring-forecast',
    },
  ]
